name: 🤖 Publish Package

on:
  workflow_call:
    inputs:
      version:
        description: 'Set the version number of the published application.'
        default: '0.0.0'
        required: false
        type: string

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    name: Docker Image

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Fetch image artifact
        uses: actions/download-artifact@v4
        with:
          name: keystone-web-docker
          path: /tmp

      - name: Load image
        run: docker load --input /tmp/keystone-web.tar

      - name: Define Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/keystone-web
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  trigger-docs:
    name: Trigger Docs
    runs-on: ubuntu-latest
    steps:
      - name: Update docs
        uses: pitt-crc/keystone-docs/.github/actions/update-action/@main
        with:
          keystone-gitops-id: ${{ secrets.KEYSTONE_GITOPS_ID }}
          keystone-gitops-pk: ${{ secrets.KEYSTONE_GITOPS_PK }}
          repo-name: keystone-web
          tag: v${{ inputs.version }}
